---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: preemptible-killer
    namespace: {{ .gkepreemptiblekiller.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: preemptible-killer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - delete
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: preemptible-killer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: preemptible-killer
subjects:
- kind: ServiceAccount
  name: preemptible-killer
  namespace: {{ .gkepreemptiblekiller.namespace }}