---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: prow-bucket-gcs-credentials
  namespace: {{ .prow.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: service-account.json
    key: {{ .prow.gcs.svcaccount.credstash.key | quote }}
{{- if hasKey .prow.gcs.svcaccount.credstash "table" }}
    table: {{ .prow.gcs.svcaccount.credstash.table | quote }}
{{- end }}
{{- if hasKey .prow.gcs.svcaccount.credstash "version" }}
    version: {{ .prow.gcs.svcaccount.credstash.version | quote }}
{{- end }}
---
{{ if .prow.slack.token }}
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: slack-token
  namespace: {{ .prow.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: token
    key: {{ .prow.slack.token.credstash.key | quote }}
{{- if hasKey .prow.slack.token.credstash "table" }}
    table: {{ .prow.slack.token.credstash.table | quote }}
{{- end }}
{{- if hasKey .prow.slack.token.credstash "version" }}
    version: {{ .prow.slack.token.credstash.version | quote }}
{{- end }}
{{ end }}
---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: github-token
  namespace: {{ .prow.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: oauth
    key: {{ .prow.github.token.credstash.key | quote }}
{{- if hasKey .prow.github.token.credstash "table" }}
    table: {{ .prow.github.token.credstash.table | quote }}
{{- end }}
{{- if hasKey .prow.github.token.credstash "version" }}
    version: {{ .prow.github.token.credstash.version | quote }}
{{- end }}
---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: github-ssh-key
  namespace: {{ .prow.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: key
    key: {{ .prow.github.sshkey.credstash.key | quote }}
{{- if hasKey .prow.github.sshkey.credstash "table" }}
    table: {{ .prow.github.sshkey.credstash.table | quote }}
{{- end }}
{{- if hasKey .prow.github.sshkey.credstash "version" }}
    version: {{ .prow.github.sshkey.credstash.version | quote }}
{{- end }}
---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: oauth-config
  namespace: {{ .prow.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: secret
    key: {{ .prow.github.oauthconfig.credstash.key | quote }}
{{- if hasKey .prow.github.oauthconfig.credstash "table" }}
    table: {{ .prow.github.oauthconfig.credstash.table | quote }}
{{- end }}
{{- if hasKey .prow.github.oauthconfig.credstash "version" }}
    version: {{ .prow.github.oauthconfig.credstash.version | quote }}
{{- end }}