{{ $root := . -}}
{{- range $key, $value := .credstashoperator.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credstash-operator-{{ $key }}
  namespace: {{ $root.credstashoperator.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: credstash-operator
      operatorInstance: {{ $key }}
  template:
    metadata:
      labels:
        name: credstash-operator
        operatorInstance: {{ $key }}
    spec:
      serviceAccountName: credstash-operator
      containers:
        - name: credstash-operator
          image: {{ $root.credstashoperator.image }}
          command:
            - credstash-operator
          args:
            - --selector-label={{ $key }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: aws-credentials-{{ $key }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "credstash-operator-{{ $key }}"
            - name: SERVICE_MONITOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8383
              protocol: TCP
            - name: cr-metrics
              containerPort: 8686
              protocol: TCP
{{ end }}