{{ $root := . -}}
{{- range $key, $value := .credstashoperator.instances }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-{{ $key }}
  namespace: {{ $root.credstashoperator.namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ $value.aws.accessid | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $value.aws.secretaccesskey | b64enc }}
  AWS_REGION: {{ $value.aws.region | b64enc }}
{{ end }}