presubmits:
  - name: validate
    context: validate
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/prow-installer.git"
    max_concurrency: 1
    trigger: "(?m)validate( please)?"
    rerun_command: "validate"
    spec:
      containers:
        - name: "validate"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - validate
  - name: test-package
    context: test-package
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/prow-installer.git"
    max_concurrency: 1
    trigger: "(?m)test-package( please)?"
    rerun_command: "test-package"
    spec:
      containers:
        - name: "test-package"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - package
  - name: test-semrelease-dryrun
    context: test-semrelease-dryrun
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/prow-installer.git"
    max_concurrency: 1
    labels:
      preset-semantic-release: "true"
    trigger: "(?m)semrelease-dryrun( please)?"
    rerun_command: "semrelease-dryrun"
    spec:
      containers:
        - name: "test-semrelease-dryrun"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - semantic-release-dry-run
postsubmits:
  - name: prow-installer-release
    labels:
      preset-semantic-release: "true"
    clone_uri: "git@github.com:ouzi-dev/prow-installer.git"
    decorate: true
    max_concurrency: 1
    branches:
      - master
    spec:
      containers:
        - name: "release"
          imagePullPolicy: Always
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - semantic-release