{{ $root := . -}}
{{- range $key, $value := .credstashoperator.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credstash-operator-{{ $key }}
  namespace: {{ $root.credstashoperator.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: credstash-operator
      operatorInstance: {{ $key }}
  template:
    metadata:
      labels:
        name: credstash-operator
        operatorInstance: {{ $key }}
    spec:
      serviceAccountName: credstash-operator
      containers:
        - name: credstash-operator
          image: {{ $root.credstashoperator.image }}
          command:
            - credstash-operator
          args:
            - --selector-label={{ $key }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: aws-credentials-{{ $key }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "credstash-operator"
{{ end }}