{{ $root := . -}}
{{ range .buildsecrets.credstashsecrets -}}
---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $root.buildsecrets.namespaceforjobs }}
  labels:
    operatorInstance: system
spec:
{{- if .type }}
  type: {{ .type }}
{{- end }}
  secrets:
{{- range .keys }}
  - name: {{ .name }}
    key: {{ .key | quote }}
    table: {{ .table | quote }}
    version: {{ .version | quote }}
{{ end -}}
{{ end -}}