---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: github-oauth-secret
  namespace: {{ .oauthproxy.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: client-id
    key: {{ .oauthproxy.clientid.credstash.key | quote }}
    table: {{ .oauthproxy.clientid.credstash.table | quote }}
    version: {{ .oauthproxy.clientid.credstash.version | quote}}
  - name: client-secret
    key: {{ .oauthproxy.clientsecret.credstash.key | quote }}
    table: {{ .oauthproxy.clientsecret.credstash.table | quote }}
    version: {{ .oauthproxy.clientsecret.credstash.version | quote }}
  - name: cookie-secret
    key: {{ .oauthproxy.cookiesecret.credstash.key | quote }}
    table: {{ .oauthproxy.cookiesecret.credstash.table | quote }}
    version: {{ .oauthproxy.cookiesecret.credstash.version | quote }}    