provider: google
google:
  project: {{ .global.gcloud.project }}
replicas: 1
metrics:
  enabled: true
policy: sync
tolerations:
  - key: cloud.google.com/gke-preemptible
    operator: Equal
    value: "true"
    effect: NoSchedule