---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: preemptible-killer-secrets
  namespace: {{ .gkepreemptiblekiller.namespace }}
  labels:
    operatorInstance: system
spec:
  secrets:
  - name: google-service-account.json
    key: {{ .gkepreemptiblekiller.svcaccount.credstash.key | quote }}
{{- if hasKey .gkepreemptiblekiller.svcaccount.credstash "table" }}
    table: {{ .gkepreemptiblekiller.svcaccount.credstash.table | quote }}
{{- end }}
{{- if hasKey .gkepreemptiblekiller.svcaccount.credstash "version" }}
    version: {{ .gkepreemptiblekiller.svcaccount.credstash.version | quote }}
{{- end }}