---
apiVersion: credstash.ouzi.tech/v1alpha1
kind: CredstashSecret
metadata:
  name: preemptible-killer-secrets
  namespace: {{ .gkepreemptiblekiller.namespace }}
spec:
  secrets:
  - name: google-service-account.json
    key: {{ .gkepreemptiblekiller.svcaccount.credstash.key | quote }}
    table: {{ .gkepreemptiblekiller.svcaccount.credstash.table | quote }}
    version: {{ .gkepreemptiblekiller.svcaccount.credstash.version | quote }}