---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preemptible-killer
  namespace: {{ .gkepreemptiblekiller.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gke-preemptible-killer
  template:
    metadata:
      labels:
        k8s-app: gke-preemptible-killer
    spec:
      serviceAccountName: preemptible-killer
      terminationGracePeriodSeconds: 300
      tolerations:
        - key: cloud.google.com/gke-preemptible
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
      - name: preemptible-killer
        image: {{ .gkepreemptiblekiller.image }}
        ports:
        - name: prom-metrics
          containerPort: 9001
        env:
        - name: DRAIN_TIMEOUT
          value: "300"
        - name: INTERVAL
          value: "600"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/preemptible-killer-secrets/google-service-account.json
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom-metrics
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: preemptible-killer-secrets
          mountPath: /etc/preemptible-killer-secrets
      volumes:
      - name: preemptible-killer-secrets
        secret:
          secretName: preemptible-killer-secrets